camera_configs:
  camera_distance: 1.5
  yaw: 0
  pitch: -30
  roll: 0
  camera_joint: 9
lidar_configs:
  lidar_joints: 8
  lidar_angle1: 45
  lidar_angle2: 135
  num_rays: 50
  ray_start_len: 0.25
  ray_len: 8
  hit_color: [1, 0, 0]  # Red
  miss_color: [0, 1, 0] # Green